services:
  - type: web
    name: clubgest
    runtime: python
    repo: https://github.com/AxelNicolas0316/clubgest
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_HOST
        value: mysql-3f49e41c-axelpsoriano03-a945.h.aivencloud.com
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value:  # <--- DÉJALO VACÍO (la contraseña se agrega manualmente en Render)
      - key: DB_NAME
        value: defaultdb
      - key: DB_PORT
        value: 18162
      - key: RENDER
        value: true