services:
  - type: web
    name: clubgest
    runtime: python
    repo: https://github.com/AxelNicolas0316/clubgest
    plan: standard
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 6 --worker-class sync --threads 2 --worker-connections 1000 --bind 0.0.0.0:10000 --timeout 60 --keep-alive 5 --access-logfile - --error-logfile - --log-level info app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DB_HOST
        value: mysql-3f49e41c-axelpsoriano03-a945.h.aivencloud.com
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value:  
      - key: DB_NAME
        value: defaultdb
      - key: DB_PORT
        value: 18162
      - key: RENDER
        value: true
      - key: SECRET_KEY
        value:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"